export const LANGUAGES: Record<string, { name: string, flag: string }> = {
  en: { name: "English", flag: "🇺🇸" },
  uk: { name: "Українська", flag: "🇺🇦" },
  de: { name: "Deutsch", flag: "🇩🇪" },
  es: { name: "Español", flag: "🇪🇸" },
  fr: { name: "Français", flag: "🇫🇷" },
  it: { name: "Italiano", flag: "🇮🇹" },
  pl: { name: "Polski", flag: "🇵🇱" },
  pt: { name: "Português", flag: "🇵🇹" },
  tr: { name: "Türkçe", flag: "🇹🇷" },
  nl: { name: "Nederlands", flag: "🇳🇱" },
  sv: { name: "Svenska", flag: "🇸🇪" },
  no: { name: "Norsk", flag: "🇳🇴" },
  da: { name: "Dansk", flag: "🇩🇰" },
  fi: { name: "Suomi", flag: "🇫🇮" },
  cs: { name: "Čeština", flag: "🇨🇿" },
  sk: { name: "Slovenčina", flag: "🇸🇰" },
  hu: { name: "Magyar", flag: "🇭🇺" },
  ro: { name: "Română", flag: "🇷🇴" },
  bg: { name: "Български", flag: "🇧🇬" },
  el: { name: "Ελληνικά", flag: "🇬🇷" },
  ja: { name: "日本語", flag: "🇯🇵" },
  ko: { name: "한국어", flag: "🇰🇷" },
  zh: { name: "中文", flag: "🇨🇳" },
  ar: { name: "العربية", flag: "🇸🇦" },
  hi: { name: "हिन्दी", flag: "🇮🇳" },
  bn: { name: "বাংলা", flag: "🇧🇩" },
  pa: { name: "ਪੰਜਾਬี", flag: "🇮🇳" },
  jv: { name: "Basa Jawa", flag: "🇮🇩" },
  ms: { name: "Bahasa Melayu", flag: "🇲🇾" },
  vi: { name: "Tiếng Việt", flag: "🇻🇳" },
  th: { name: "ไทย", flag: "🇹🇭" },
  id: { name: "Bahasa Indonesia", flag: "🇮🇩" },
  he: { name: "עברית", flag: "🇮🇱" },
  fa: { name: "فارسی", flag: "🇮🇷" },
  ur: { name: "اردو", flag: "🇵🇰" },
  sw: { name: "Kiswahili", flag: "🇰🇪" },
  am: { name: "አማርኛ", flag: "🇪🇹" },
  yo: { name: "Yorùbá", flag: "🇳🇬" },
  ig: { name: "Igbo", flag: "🇳🇬" },
  ha: { name: "Hausa", flag: "🇳🇬" },
  az: { name: "Azərbaycanca", flag: "🇦🇿" },
  ka: { name: "ქართული", flag: "🇬🇪" },
  hy: { name: "Հայերեն", flag: "🇦🇲" },
  uz: { name: "O'zbekcha", flag: "🇺🇿" },
  kk: { name: "Қазақ тілі", flag: "🇰🇿" },
  sr: { name: "Српски", flag: "🇷🇸" },
  hr: { name: "Hrvatski", flag: "🇭🇷" },
  bs: { name: "Bosanski", flag: "🇧🇦" },
  sq: { name: "Shqip", flag: "🇦🇱" },
  mk: { name: "Македонски", flag: "🇲🇰" },
  lt: { name: "Lietuvių", flag: "🇱🇹" },
  lv: { name: "Latviešu", flag: "🇱🇻" },
  et: { name: "Eesti", flag: "🇪🇪" },
  is: { name: "Íslenska", flag: "🇮🇸" },
  ga: { name: "Gaeilge", flag: "🇮🇪" },
  cy: { name: "Cymraeg", flag: "🇬🇧" },
  mt: { name: "Malti", flag: "🇲🇹" },
  af: { name: "Afrikaans", flag: "🇿🇦" },
  zu: { name: "isiZulu", flag: "🇿🇦" },
  xh: { name: "isiXhosa", flag: "🇿🇦" },
};

export const translations: Record<string, any> = {
  en: {
    title: "HELPER FOR TEENS",
    calculator: "Scientific Calculator",
    trigTable: "Trigonometry Table",
    translator: "AI Translator",
    auth: "Authentication",
    login: "Login",
    register: "Register",
    email: "Email",
    password: "Password",
    logout: "Logout",
    theme: "Theme",
    lang: "Language",
    solve: "Solve",
    result: "Result",
    translate: "Translate",
    sourceText: "Enter text to translate...",
    targetLang: "Target Language",
    degree: "Degrees",
    rad: "Radians",
    sin: "Sin",
    cos: "Cos",
    tan: "Tan",
    cot: "Cot",
    xp: "XP",
    level: "Level",
    welcome: "Welcome back",
    noAccount: "No account?",
    hasAccount: "Already have an account?",
    squaresCubes: "Squares & Cubes",
    writers: "Ukrainian Writers",
    nmtTest: "NMT Preparation",
    history: "History Dates",
    graph: "Graph Plotter",
    fractions: "Fraction Calculator",
    countries: "Countries & Capitals",
    search: "Search...",
    irregularVerbs: "Irregular Verbs (EN)",
    germanCases: "German Cases",
    unifiedCalc: "Unified Calculator",
    discriminant: "Discriminant (D)",
    solveEq: "Solve Equation",
    credits: "Created by AI & Maurice Nardly",
    generateTest: "Generate New NMT Test",
    historicalFigures: "Historical Figures",
    factOfTheHour: "Fact of the Hour",
    refresh: "Refresh",
    detectLang: "Detect Language",
    clear: "Clear",
    v1: "Base Form",
    v2: "Past Simple",
    v3: "Past Participle",
    translation: "Translation",
    nickname: "Nickname",
    avatar: "Avatar",
    country: "Country",
    chat: "Teen Chat",
    geometry: "Geometry Calculator",
    formulas: "Math Formulas",
    slang: "Slang Library",
    dailyQuote: "Quote of the Day",
    bibleVerse: "Bible Verse of the Day",
    volume: "Volume",
    area: "Area",
    perimeter: "Perimeter",
    radius: "Radius",
    width: "Width",
    height: "Height",
    length: "Length",
    side: "Side",
    ukGrammar: "Ukrainian Grammar",
    germanCasesTable: "German Cases Table",
    fractionCalc: "Fraction Calculator",
    graphPlotter: "Graph Plotter",
    discriminantCalc: "Discriminant Calculator",
    historyTitle: "History",
    savedTitle: "Saved",
    close: "Close",
    noItems: "No items yet",
    fetchingWiki: "Fetching from Wikipedia...",
    openWiki: "Open on Wikipedia",
    num1: "Numerator 1",
    den1: "Denominator 1",
    num2: "Numerator 2",
    den2: "Denominator 2",
    func: "Function (e.g. x*x)",
    plot: "Plot",
    typeMessage: "Type a message...",
    copied: "Copied!",
    checkResult: "Check Result",
    works: "Works",
    case: "Case",
    m: "M",
    f: "F",
    n: "N",
    pl: "Pl",
  },
  uk: {
    title: "HELPER FOR TEENS",
    calculator: "Науковий калькулятор",
    trigTable: "Таблиця тригонометрії",
    translator: "AI Перекладач",
    auth: "Авторизація",
    login: "Увійти",
    register: "Реєстрація",
    email: "Пошта",
    password: "Пароль",
    logout: "Вийти",
    theme: "Тема",
    lang: "Мова",
    solve: "Розв'язати",
    result: "Результат",
    translate: "Перекласти",
    sourceText: "Введіть текст для перекладу...",
    targetLang: "Мова перекладу",
    degree: "Градуси",
    rad: "Радіани",
    sin: "Sin",
    cos: "Cos",
    tan: "Tan",
    cot: "Cot",
    xp: "XP",
    level: "Рівень",
    welcome: "З поверненням",
    noAccount: "Немає акаунту?",
    hasAccount: "Вже є акаунт?",
    squaresCubes: "Квадрати та Куби",
    writers: "Українські Письменники",
    nmtTest: "Підготовка до НМТ",
    history: "Історичні Дати",
    graph: "Побудова Графіків",
    fractions: "Калькулятор Дробів",
    countries: "Країни та Столиці",
    search: "Пошук...",
    irregularVerbs: "Неправильні дієслова (EN)",
    germanCases: "Відмінювання в німецькій",
    unifiedCalc: "Універсальний калькулятор",
    discriminant: "Дискримінант (D)",
    solveEq: "Розв'язати рівняння",
    credits: "Створено AI та Морісом Нардлі",
    generateTest: "Згенерувати новий тест НМТ",
    historicalFigures: "Історичні постаті",
    factOfTheHour: "Факт години",
    refresh: "Оновити",
    detectLang: "Визначити мову",
    clear: "Очистити",
    v1: "I форма",
    v2: "II форма",
    v3: "III форма",
    translation: "Переклад",
    nickname: "Нікнейм",
    avatar: "Аватар",
    country: "Країна",
    chat: "Чат підлітків",
    geometry: "Геометричний калькулятор",
    formulas: "Математичні формули",
    slang: "Бібліотека сленгу",
    dailyQuote: "Цитата дня",
    bibleVerse: "Біблійний вірш дня",
    volume: "Об'єм",
    area: "Площа",
    perimeter: "Периметр",
    radius: "Радіус",
    width: "Ширина",
    height: "Висота",
    length: "Довжина",
    side: "Сторона",
    ukGrammar: "Граматика української мови",
    germanCasesTable: "Таблиця німецьких відмінків",
    fractionCalc: "Калькулятор дробів",
    graphPlotter: "Побудова графіків",
    discriminantCalc: "Калькулятор дискримінанту",
    historyTitle: "Історія",
    savedTitle: "Збережені",
    close: "Закрити",
    noItems: "Поки що порожньо",
    fetchingWiki: "Отримуємо дані з Вікіпедії...",
    openWiki: "Відкрити у Вікіпедії",
    num1: "Чисельник 1",
    den1: "Знаменник 1",
    num2: "Чисельник 2",
    den2: "Знаменник 2",
    func: "Функція (напр. x*x)",
    plot: "Побудувати",
    typeMessage: "Введіть повідомлення...",
    copied: "Скопійовано!",
    checkResult: "Перевірити результат",
    works: "Твори",
    case: "Відмінок",
    m: "Ч",
    f: "Ж",
    n: "С",
    pl: "Мн",
  },
};

export type Language = string;

export const MATH_FORMULAS = [
  { name: "Square Area", formula: "S = a²" },
  { name: "Rectangle Area", formula: "S = a * b" },
  { name: "Circle Area", formula: "S = π * r²" },
  { name: "Triangle Area", formula: "S = 0.5 * b * h" },
  { name: "Pythagorean Theorem", formula: "a² + b² = c²" },
  { name: "Quadratic Formula", formula: "x = (-b ± √D) / 2a" },
  { name: "Sphere Volume", formula: "V = (4/3) * π * r³" },
  { name: "Cylinder Volume", formula: "V = π * r² * h" },
  { name: "Cone Volume", formula: "V = (1/3) * π * r² * h" },
  { name: "Perimeter of Square", formula: "P = 4a" },
  { name: "Perimeter of Rectangle", formula: "P = 2(a + b)" },
  { name: "Circumference", formula: "C = 2πr" },
  { name: "Slope of Line", formula: "m = (y2 - y1) / (x2 - x1)" },
  { name: "Distance Formula", formula: "d = √((x2-x1)² + (y2-y1)²)" },
  { name: "Midpoint Formula", formula: "M = ((x1+x2)/2, (y1+y2)/2)" },
  { name: "Sum of Angles in Triangle", formula: "180°" },
  { name: "Sum of Angles in Quadrilateral", formula: "360°" },
  { name: "Area of Trapezoid", formula: "S = ((a+b)/2) * h" },
  { name: "Volume of Cube", formula: "V = a³" },
  { name: "Surface Area of Sphere", formula: "S = 4πr²" },
  { name: "Logarithm Identity", formula: "log(ab) = log a + log b" },
  { name: "Exponent Rule", formula: "a^m * a^n = a^(m+n)" },
  { name: "Trig Identity", formula: "sin²x + cos²x = 1" },
  { name: "Double Angle Sin", formula: "sin 2x = 2 sin x cos x" },
  { name: "Double Angle Cos", formula: "cos 2x = cos²x - sin²x" },
  { name: "Law of Sines", formula: "a/sin A = b/sin B = c/sin C" },
  { name: "Law of Cosines", formula: "c² = a² + b² - 2ab cos C" },
  { name: "Area of Parallelogram", formula: "S = b * h" },
  { name: "Volume of Prism", formula: "V = B * h" },
  { name: "Volume of Pyramid", formula: "V = (1/3) * B * h" },
  { name: "Arithmetic Sequence", formula: "an = a1 + (n-1)d" },
  { name: "Geometric Sequence", formula: "an = a1 * r^(n-1)" },
  { name: "Sum of Arithmetic", formula: "Sn = (n/2)(a1 + an)" },
  { name: "Sum of Geometric", formula: "Sn = a1(1-r^n)/(1-r)" },
  { name: "Permutations", formula: "nPr = n! / (n-r)!" },
  { name: "Combinations", formula: "nCr = n! / (r!(n-r)!)" },
  { name: "Probability", formula: "P(A) = n(A) / n(S)" },
  { name: "Derivative of x^n", formula: "nx^(n-1)" },
  { name: "Integral of x^n", formula: "x^(n+1)/(n+1) + C" },
  { name: "Euler's Formula", formula: "e^(iπ) + 1 = 0" },
  { name: "Compound Interest", formula: "A = P(1 + r/n)^(nt)" },
  { name: "Density", formula: "ρ = m / V" },
  { name: "Force", formula: "F = m * a" },
  { name: "Work", formula: "W = F * d" },
  { name: "Power", formula: "P = W / t" },
  { name: "Kinetic Energy", formula: "KE = 0.5 * m * v²" },
  { name: "Potential Energy", formula: "PE = m * g * h" },
  { name: "Ohm's Law", formula: "V = I * R" },
  { name: "Speed", formula: "v = d / t" },
  { name: "Acceleration", formula: "a = (v - u) / t" },
  { name: "Pressure", formula: "P = F / A" },
  { name: "Momentum", formula: "p = m * v" },
  { name: "Wave Speed", formula: "v = f * λ" },
  { name: "Frequency", formula: "f = 1 / T" },
  { name: "Efficiency", formula: "Eff = (Useful / Total) * 100%" },
  { name: "Torque", formula: "τ = r * F * sin θ" },
  { name: "Centripetal Force", formula: "Fc = m * v² / r" },
  { name: "Gravitational Force", formula: "F = G * m1 * m2 / r²" },
  { name: "Heat Energy", formula: "Q = m * c * ΔT" },
  { name: "Ideal Gas Law", formula: "PV = nRT" },
];

export const IRREGULAR_VERBS = [
  { v1: "be", v2: "was/were", v3: "been", t: { en: "be", uk: "бути" } },
  { v1: "become", v2: "became", v3: "become", t: { en: "become", uk: "ставати" } },
  { v1: "begin", v2: "began", v3: "begun", t: { en: "begin", uk: "починати" } },
  { v1: "break", v2: "broke", v3: "broken", t: { en: "break", uk: "ламати" } },
  { v1: "bring", v2: "brought", v3: "brought", t: { en: "bring", uk: "приносити" } },
  { v1: "build", v2: "built", v3: "built", t: { en: "build", uk: "будувати" } },
  { v1: "buy", v2: "bought", v3: "bought", t: { en: "buy", uk: "купувати" } },
  { v1: "catch", v2: "caught", v3: "caught", t: { en: "catch", uk: "ловити" } },
  { v1: "choose", v2: "chose", v3: "chosen", t: { en: "choose", uk: "вибирати" } },
  { v1: "come", v2: "came", v3: "come", t: { en: "come", uk: "приходити" } },
  { v1: "do", v2: "did", v3: "done", t: { en: "do", uk: "робити" } },
  { v1: "drink", v2: "drank", v3: "drunk", t: { en: "drink", uk: "пити" } },
  { v1: "drive", v2: "drove", v3: "driven", t: { en: "drive", uk: "водити" } },
  { v1: "eat", v2: "ate", v3: "eaten", t: { en: "eat", uk: "їсти" } },
  { v1: "fall", v2: "fell", v3: "fallen", t: { en: "fall", uk: "падати" } },
  { v1: "feel", v2: "felt", v3: "felt", t: { en: "feel", uk: "відчувати" } },
  { v1: "find", v2: "found", v3: "found", t: { en: "find", uk: "знаходити" } },
  { v1: "fly", v2: "flew", v3: "flown", t: { en: "fly", uk: "літати" } },
  { v1: "forget", v2: "forgot", v3: "forgotten", t: { en: "forget", uk: "забувати" } },
  { v1: "get", v2: "got", v3: "got", t: { en: "get", uk: "отримувати" } },
  { v1: "give", v2: "gave", v3: "given", t: { en: "give", uk: "давати" } },
  { v1: "go", v2: "went", v3: "gone", t: { en: "go", uk: "йти" } },
  { v1: "have", v2: "had", v3: "had", t: { en: "have", uk: "мати" } },
  { v1: "hear", v2: "heard", v3: "heard", t: { en: "hear", uk: "чути" } },
  { v1: "know", v2: "knew", v3: "known", t: { en: "know", uk: "знати" } },
  { v1: "leave", v2: "left", v3: "left", t: { en: "leave", uk: "залишати" } },
  { v1: "make", v2: "made", v3: "made", t: { en: "make", uk: "робити" } },
  { v1: "meet", v2: "met", v3: "met", t: { en: "meet", uk: "зустрічати" } },
  { v1: "pay", v2: "paid", v3: "paid", t: { en: "pay", uk: "платити" } },
  { v1: "read", v2: "read", v3: "read", t: { en: "read", uk: "читати" } },
  { v1: "run", v2: "ran", v3: "run", t: { en: "run", uk: "бігати" } },
  { v1: "say", v2: "said", v3: "said", t: { en: "say", uk: "казати" } },
  { v1: "see", v2: "saw", v3: "seen", t: { en: "see", uk: "бачити" } },
  { v1: "send", v2: "sent", v3: "sent", t: { en: "send", uk: "надсилати" } },
  { v1: "sing", v2: "sang", v3: "sung", t: { en: "sing", uk: "співати" } },
  { v1: "sit", v2: "sat", v3: "sat", t: { en: "sit", uk: "сидіти" } },
  { v1: "sleep", v2: "slept", v3: "slept", t: { en: "sleep", uk: "спати" } },
  { v1: "speak", v2: "spoke", v3: "spoken", t: { en: "speak", uk: "говорити" } },
  { v1: "spend", v2: "spent", v3: "spent", t: { en: "spend", uk: "витрачати" } },
  { v1: "swim", v2: "swam", v3: "swum", t: { en: "swim", uk: "плавати" } },
  { v1: "take", v2: "took", v3: "taken", t: { en: "take", uk: "брати" } },
  { v1: "teach", v2: "taught", v3: "taught", t: { en: "teach", uk: "вчити" } },
  { v1: "tell", v2: "told", v3: "told", t: { en: "tell", uk: "розповідати" } },
  { v1: "think", v2: "thought", v3: "thought", t: { en: "think", uk: "думати" } },
  { v1: "understand", v2: "understood", v3: "understood", t: { en: "understand", uk: "розуміти" } },
  { v1: "write", v2: "wrote", v3: "written", t: { en: "write", uk: "писати" } },
];

export const UKRAINIAN_GRAMMAR = [
  { title: "Подвоєння приголосних", rule: "Приголосні подвоюються на межі значущих частин слова: безсонний (без- + сон), віддати (від- + дати)." },
  { title: "Спрощення в групах приголосних", rule: "У групах приголосних -стн-, -стл- приголосний [т] випадає: вість — вісник, щастя — щасливий." },
  { title: "Правопис складних слів", rule: "Разом пишуться слова з першою частиною авіа-, авто-, біо-, відео-, макро-, мікро-." },
  { title: "Тире між підметом і присудком", rule: "Тире ставиться, якщо підмет і присудок виражені іменником у назовному відмінку: Київ — столиця України." },
];

export const GERMAN_CASES = [
  { case: "Nominativ", question: "Wer? Was?", m: "der / ein", f: "die / eine", n: "das / ein", pl: "die / -" },
  { case: "Genitiv", question: "Wessen?", m: "des / eines", f: "der / einer", n: "des / eines", pl: "der / -" },
  { case: "Dativ", question: "Wem?", m: "dem / einem", f: "der / einer", n: "dem / einem", pl: "den / -n" },
  { case: "Akkusativ", question: "Wen? Was?", m: "den / einen", f: "die / eine", n: "das / ein", pl: "die / -" },
];

export const SLANG_LIBRARY = [
  { word: "No cap", meaning: "No lie / For real" },
  { word: "Bet", meaning: "Agreement / Approval" },
  { word: "Sus", meaning: "Suspicious" },
  { word: "Bussin", meaning: "Really good (usually food)" },
  { word: "Sheesh", meaning: "Expression of shock or amazement" },
  { word: "Simp", meaning: "Someone who does too much for their crush" },
  { word: "Stan", meaning: "An overzealous fan" },
  { word: "Yeet", meaning: "To throw something with force" },
  { word: "Flex", meaning: "To show off" },
  { word: "Lowkey", meaning: "Secretly or discreetly" },
  { word: "Highkey", meaning: "Openly or obviously" },
  { word: "Slay", meaning: "To do something exceptionally well" },
  { word: "Tea", meaning: "Gossip" },
  { word: "Vibe check", meaning: "Assessing someone's mood" },
  { word: "Ghost", meaning: "To stop responding to someone" },
];
